.TH "source Directory Reference" 3 "Version V4.2.0" "Chess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBishop\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBoard\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBotPlayer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBChessGame\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHumanPlayer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBKing\&.cpp\fP"
.br
.ti -1c
.RI "file \fBKnight\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMove\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPawn\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPiece\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPlayer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBQueen\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRook\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTwoPlayerGame\&.cpp\fP"
.br
.in -1c
