.TH "Board.cpp" 3 "Version V4.2.0" "Chess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Board.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./include/Board\&.h'\fP
.br
\fR#include '\&.\&./include/Piece\&.h'\fP
.br
\fR#include '\&.\&./include/Player\&.h'\fP
.br
\fR#include '\&.\&./include/Pawn\&.h'\fP
.br
\fR#include '\&.\&./include/Rook\&.h'\fP
.br
\fR#include '\&.\&./include/Knight\&.h'\fP
.br
\fR#include '\&.\&./include/Bishop\&.h'\fP
.br
\fR#include '\&.\&./include/Queen\&.h'\fP
.br
\fR#include '\&.\&./include/King\&.h'\fP
.br
\fR#include '\&.\&./include/Move\&.h'\fP
.br
\fR#include '\&.\&./dependencies/Style\&.hpp'\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <cstdlib>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLogMoveRecord\fP (const \fBMoveRecord\fP &record)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void LogMoveRecord (const \fBMoveRecord\fP & record)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess Game from the source code\&.
