.TH "/home/huplo/Coding/Projects/C++/chess-game/include/ChessGame.h" 3 "Version V4.2.0" "Chess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/huplo/Coding/Projects/C++/chess-game/include/ChessGame.h
.SH SYNOPSIS
.br
.PP
\fR#include 'CanvasApp\&.h'\fP
.br
\fR#include 'TwoPlayerGame\&.h'\fP
.br
\fR#include 'Board\&.h'\fP
.br
\fR#include <chrono>\fP
.br
\fR#include <atomic>\fP
.br
\fR#include <thread>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChessGame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chess Game from the source code\&.
