.TH "ChessGame.cpp" 3 "Version V4.2.0" "Chess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChessGame.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./include/ChessGame\&.h'\fP
.br
\fR#include '\&.\&./include/HumanPlayer\&.h'\fP
.br
\fR#include '\&.\&./include/BotPlayer\&.h'\fP
.br
\fR#include <sstream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess Game from the source code\&.
