.TH "HumanPlayer.cpp" 3 "Version V4.2.0" "Chess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HumanPlayer.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./include/HumanPlayer\&.h'\fP
.br
\fR#include '\&.\&./dependencies/Style\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess Game from the source code\&.
