.TH "/home/huplo/Coding/Projects/C++/chess-game/include/HumanPlayer.h" 3 "Version V4.2.0" "Chess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/huplo/Coding/Projects/C++/chess-game/include/HumanPlayer.h
.SH SYNOPSIS
.br
.PP
\fR#include 'Player\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHumanPlayer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chess Game from the source code\&.
