.TH "MoveRecord" 3 "Version V4.2.0" "Chess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveRecord
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Board\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx0\fP"
.br
.ti -1c
.RI "int \fBy0\fP"
.br
.ti -1c
.RI "int \fBx1\fP"
.br
.ti -1c
.RI "int \fBy1\fP"
.br
.ti -1c
.RI "\fBPiece\fP * \fBmovedPiece\fP"
.br
.ti -1c
.RI "\fBPiece\fP * \fBcapturedPiece\fP"
.br
.ti -1c
.RI "\fBPiece\fP * \fBreplacementPiece\fP"
.br
.ti -1c
.RI "bool \fBenPassantUsed\fP"
.br
.ti -1c
.RI "bool \fBprevEnPassantAvailable\fP"
.br
.ti -1c
.RI "int \fBprevEnPassantX\fP"
.br
.ti -1c
.RI "int \fBprevEnPassantY\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBPiece\fP* MoveRecord::capturedPiece"

.SS "bool MoveRecord::enPassantUsed"

.SS "\fBPiece\fP* MoveRecord::movedPiece"

.SS "bool MoveRecord::prevEnPassantAvailable"

.SS "int MoveRecord::prevEnPassantX"

.SS "int MoveRecord::prevEnPassantY"

.SS "\fBPiece\fP* MoveRecord::replacementPiece"

.SS "int MoveRecord::x0"

.SS "int MoveRecord::x1"

.SS "int MoveRecord::y0"

.SS "int MoveRecord::y1"


.SH "Author"
.PP 
Generated automatically by Doxygen for Chess Game from the source code\&.
