.TH "/home/huplo/Coding/Projects/C++/chess-game/include/Move.h" 3 "Version V4.2.0" "Chess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/huplo/Coding/Projects/C++/chess-game/include/Move.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <stdexcept>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMove\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Chess Game from the source code\&.
