.TH "Pawn.cpp" 3 "Version V4.2.0" "Chess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pawn.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./include/Pawn\&.h'\fP
.br
\fR#include '\&.\&./include/Rook\&.h'\fP
.br
\fR#include '\&.\&./include/Bishop\&.h'\fP
.br
\fR#include '\&.\&./include/Knight\&.h'\fP
.br
\fR#include '\&.\&./include/Queen\&.h'\fP
.br
\fR#include '\&.\&./include/Board\&.h'\fP
.br
\fR#include '\&.\&./include/Move\&.h'\fP
.br
\fR#include <cmath>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpromote\fP (\fBPiece\fP **setReplacement, \fBPieceColor\fP color)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void promote (\fBPiece\fP ** setReplacement, \fBPieceColor\fP color)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess Game from the source code\&.
