.TH "/home/huplo/Coding/Projects/C++/chess-game/include/Piece.h" 3 "Version V4.2.0" "Chess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/huplo/Coding/Projects/C++/chess-game/include/Piece.h
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./dependencies/Style\&.hpp'\fP
.br
\fR#include 'Board\&.h'\fP
.br
\fR#include 'Move\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPiece\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBColor\fP \fBPieceColor\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBColor\fP \fBPieceColor\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess Game from the source code\&.
