.TH "/home/huplo/Coding/Projects/C++/chess-game/dependencies/Style.hpp" 3 "Version V4.2.0" "Chess Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/huplo/Coding/Projects/C++/chess-game/dependencies/Style.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <vector>\fP
.br
\fR#include <regex>\fP
.br
\fR#include <limits>\fP
.br
\fR#include <cstdio>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStyle\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBColor\fP { \fBWHITE\fP, \fBBLACK\fP, \fBRED\fP, \fBGREEN\fP, \fBBLUE\fP, \fBCYAN\fP, \fBMAGENTA\fP, \fBYELLOW\fP, \fBLIGHT_GREEN\fP, \fBPINK\fP, \fBDEFAULT\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBColor\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIWHITE \fP
.TP
\f(BIBLACK \fP
.TP
\f(BIRED \fP
.TP
\f(BIGREEN \fP
.TP
\f(BIBLUE \fP
.TP
\f(BICYAN \fP
.TP
\f(BIMAGENTA \fP
.TP
\f(BIYELLOW \fP
.TP
\f(BILIGHT_GREEN \fP
.TP
\f(BIPINK \fP
.TP
\f(BIDEFAULT \fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Chess Game from the source code\&.
